导入 PyTorch 库，正式开始学习PyTorch库各种实用方法

In [1]:
import torch

确认是否使用CUDA

In [2]:
print(torch.cuda.is_available())

True


1.创建随机张量(tensor)

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)
#创建一个两行三列的随机张量，填充随机数
#Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
print(a)
print(b)
#计算张量a中所有数据的和，用type函数得到数据类型，可知返回值仍然是一个张量
print(type(a.sum()),a.sum())
#访问a张量第二行第二列的元素
print(type(a[1,1]),a[1,1])
#a张量与b张量相乘
print(type(a*b),a*b)
#获取张量a中的最大值
print(a.max())
#数据处理
print(a[0,0]<1)
print(a[0,0]+1)

tensor([[0.3138, 0.5150, 0.3090],
        [0.2501, 0.4245, 0.9350]])
tensor([[0.6040, 0.5937, 0.1508],
        [0.2523, 0.4815, 0.2778]])
<class 'torch.Tensor'> tensor(2.7474)
<class 'torch.Tensor'> tensor(0.4245)
<class 'torch.Tensor'> tensor([[0.1895, 0.3058, 0.0466],
        [0.0631, 0.2044, 0.2598]])
tensor(0.9350)
tensor(True)
tensor(1.3138)


导入 Numpy

In [17]:
import numpy as np

2.从 NumPy 数组创建张量

In [18]:
numpy_array = np.array([[1, 1], [2, 2]])
print(type(numpy_array),numpy_array)
tensor = torch.from_numpy(numpy_array)
print(type(tensor),tensor)
#可以看到通过torch.from_numpy方法，我们将ndarray转化成用于PyTorch的tensor了

<class 'numpy.ndarray'> [[1 1]
 [2 2]]
<class 'torch.Tensor'> tensor([[1, 1],
        [2, 2]])


3.张量的堆叠

In [37]:
#创建两个一维张量
a = torch.tensor([1,2,3,4,0.5])
b = torch.tensor([5,4,3,2,1])
#操作一：dim(dimension)=0
c = torch.stack([a,b],dim=0)
print(c)
#操作一：dim(dimension)=1(用来生成点集)
d = torch.stack([a,b],dim=1)
print(d)
_, indexes = torch.topk(a, 3, largest=False)
print(indexes)
print(a[indexes])

tensor([[1.0000, 2.0000, 3.0000, 4.0000, 0.5000],
        [5.0000, 4.0000, 3.0000, 2.0000, 1.0000]])
tensor([[1.0000, 5.0000],
        [2.0000, 4.0000],
        [3.0000, 3.0000],
        [4.0000, 2.0000],
        [0.5000, 1.0000]])
tensor([4, 0, 1])
tensor([0.5000, 1.0000, 2.0000])


4.zip压缩

In [33]:
x_train = torch.tensor([1.2, 2.1, 3.3])
y_train = torch.tensor([2.3, 1.2, 4.2])
s = list(zip(x_train, y_train))
print(s)

[(tensor(1.2000), tensor(2.3000)), (tensor(2.1000), tensor(1.2000)), (tensor(3.3000), tensor(4.2000))]
