导入 PyTorch 库，正式开始学习PyTorch库各种实用方法

In [1]:
import torch

确认是否使用CUDA

In [2]:
print(torch.__version__)
print(torch.cuda.is_available())

2.7.1+cu126
True


1.创建随机张量(tensor)

In [3]:
a = torch.rand(2,3)
b = torch.rand(2,3)
#创建一个两行三列的随机张量，填充随机数
print(torch.rand(1,4))
#Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
print(a)
print(b)
#计算张量a中所有数据的和，用type函数得到数据类型，可知返回值仍然是一个张量
print(type(a.sum()),a.sum())
#访问a张量第二行第二列的元素
print(type(a[1,1]),a[1,1])
#a张量与b张量相乘
print(type(a*b),a*b)
#获取张量a中的最大值
print(a.max())
#数据处理
print(a[0,0]<1)
print(a[0,0]+1)

tensor([[0.5363, 0.8077, 0.3632],
        [0.0530, 0.6440, 0.3162]])
tensor([[0.5193, 0.1359, 0.2991],
        [0.7167, 0.7131, 0.8786]])
<class 'torch.Tensor'> tensor(2.7203)
<class 'torch.Tensor'> tensor(0.6440)
<class 'torch.Tensor'> tensor([[0.2785, 0.1098, 0.1086],
        [0.0380, 0.4593, 0.2778]])
tensor(0.8077)
tensor(True)
tensor(1.5363)


导入 Numpy

In [4]:
import numpy as np

2.从 NumPy 数组创建张量

In [5]:
numpy_array = np.array([[1, 1], [2, 2]])
print(type(numpy_array),numpy_array)
tensor = torch.from_numpy(numpy_array)
print(type(tensor),tensor)
#可以看到通过torch.from_numpy方法，我们将ndarray转化成用于PyTorch的tensor了

<class 'numpy.ndarray'> [[1 1]
 [2 2]]
<class 'torch.Tensor'> tensor([[1, 1],
        [2, 2]], dtype=torch.int32)


3.张量的堆叠

In [6]:
#创建两个一维张量
a = torch.tensor([1,2,3,4,0.5])
b = torch.tensor([5,4,3,2,1])
#操作一：dim(dimension)=0
c = torch.stack([a,b],dim=0)
print(c)
#操作一：dim(dimension)=1(用来生成点集)
d = torch.stack([a,b],dim=1)
print(d)
_, indexes = torch.topk(a, 3, largest=False)
print(indexes)
print(a[indexes])

tensor([[1.0000, 2.0000, 3.0000, 4.0000, 0.5000],
        [5.0000, 4.0000, 3.0000, 2.0000, 1.0000]])
tensor([[1.0000, 5.0000],
        [2.0000, 4.0000],
        [3.0000, 3.0000],
        [4.0000, 2.0000],
        [0.5000, 1.0000]])
tensor([4, 0, 1])
tensor([0.5000, 1.0000, 2.0000])


4.zip压缩

In [7]:
x_train = torch.tensor([1.2, 2.1, 3.3])
y_train = torch.tensor([2.3, 1.2, 4.2])
s = list(zip(x_train, y_train))
print(s)

[(tensor(1.2000), tensor(2.3000)), (tensor(2.1000), tensor(1.2000)), (tensor(3.3000), tensor(4.2000))]


In [8]:
outputs = torch.tensor([[ 1.7846e+01, -4.7308e+00,  2.6316e+00, -9.4850e+00, -9.8706e+00,
          3.2438e+00,  6.6915e-01, -2.5023e+00,  3.5716e+00, -3.5058e+00],
        [ 3.7935e+00,  1.0153e+00,  2.5949e+00, -3.9824e+00,  1.6886e+00,
         -5.1823e-01,  7.1669e+00, -6.2695e+00,  4.5346e+00, -4.0652e+00],
        [ 5.6180e-01, -3.4796e+00,  1.5442e+01,  3.1205e+00, -2.0939e+00,
         -3.7801e+00,  2.3330e-01, -3.6572e+00,  4.4676e+00, -6.8169e+00],
        [-3.2702e+00, -5.8869e+00,  5.3376e-01,  5.9368e+00, -4.8745e+00,
          1.8042e+01,  2.4282e+00, -1.3610e+01,  7.5109e+00,  2.4457e+00],
        [ 1.7499e+00,  8.5935e-02,  4.6416e+00,  2.9436e+00, -6.0575e+00,
         -3.0846e+00, -4.5330e+00, -6.8919e-01,  9.9885e+00, -3.5017e+00],
        [-1.7496e+00,  3.8967e-01,  6.1398e+00,  2.7934e+00, -7.9389e+00,
         -8.7388e+00, -1.8663e+01,  1.2507e+01,  2.8253e+00,  1.0769e+00],
        [-3.3133e+00, -4.5476e+00,  2.8540e+00,  1.4397e+01, -8.2785e+00,
          8.8406e-01, -1.1041e+01,  1.7345e+00,  5.5703e+00, -2.5262e-01],
        [-5.7441e+00,  1.0771e+01, -2.1515e+00,  8.6160e-02,  2.1243e+00,
         -3.3742e+00, -2.5057e+00,  4.8419e-01,  1.7179e+00, -6.1388e-01],
        [-5.7307e+00, -1.8500e+00,  3.5212e+00,  1.4615e+01, -1.1603e+01,
         -2.8595e+00, -2.1660e+01,  6.1025e+00,  4.4296e+00,  5.5269e+00],
        [ 7.5266e-01,  8.2718e-01, -1.2652e+00, -1.3892e+00,  3.3815e+00,
          1.4621e+00,  2.6979e+00, -2.8999e+00,  1.0703e+01, -4.8646e+00],
        [ 1.3007e+00, -1.7331e+00,  3.9294e+00,  1.4033e+01, -1.0857e+01,
          3.6412e+00, -8.0091e+00, -3.2617e+00, -4.1802e+00, -1.8758e+00],
        [ 7.9802e-01, -1.1267e+00,  5.5216e-01, -1.0852e+01,  1.6241e+01,
         -4.2380e+00,  3.7388e+00,  2.3807e+00, -6.0003e-01,  1.5175e+00],
        [-3.4204e+00, -8.8607e+00,  2.8530e+00,  3.3968e+00, -9.6567e+00,
          5.9686e+00, -2.3284e+00, -2.3228e+00,  1.7866e+01,  1.0649e+00],
        [ 3.0881e-01, -5.1752e+00,  5.1540e-01,  2.4234e-01, -1.7800e+00,
         -6.1800e+00, -1.6433e+01,  1.3651e+01,  3.3136e+00,  4.2522e+00],
        [-7.9813e+00,  6.4516e+00,  1.7802e+01,  8.0929e+00, -9.0777e+00,
         -9.0352e+00, -1.5737e+01,  4.3635e+00,  4.9967e+00, -6.2814e+00],
        [-5.2274e+00, -9.1206e+00, -3.5283e+00,  3.6141e+00,  7.3717e-01,
          4.9999e+00, -7.7901e+00,  3.2612e+00,  3.0959e-01,  1.1760e+01],
        [-4.8618e+00, -1.0161e+00, -3.2540e+00,  2.6996e+00,  2.3037e+00,
          4.4036e+00, -3.6742e+00,  5.8451e-01,  2.1330e+00,  3.2497e+00],
        [ 1.1836e+00, -7.5136e+00,  4.1336e+00,  3.4067e+00, -1.5235e+00,
         -5.5120e+00, -7.1419e+00,  1.3141e+00,  1.1291e+01,  3.5359e+00],
        [-6.5015e+00,  5.6060e-02, -3.3786e+00, -6.4027e-01,  1.0015e+01,
          7.7454e-01, -4.0367e+00,  1.3372e+00,  1.4216e+00,  7.6367e+00],
        [ 1.1464e+00, -4.7841e+00,  3.1230e+00,  3.2161e+00, -5.4257e+00,
          8.0491e-01, -2.3155e+00, -1.7025e+00,  1.2434e+01, -1.3933e+00],
        [-6.1742e+00, -7.4058e+00, -1.5000e+00,  9.7331e-02,  1.9800e+00,
          1.6966e+00, -4.5717e+00,  3.0686e+00,  4.8343e+00,  1.0436e+01],
        [-4.9625e+00,  1.0049e+01, -7.7686e-01, -1.6574e-01,  1.9607e+00,
         -5.2862e+00, -4.6606e+00,  3.5905e-01,  3.5169e+00,  9.9402e-01],
        [ 1.9583e+00,  4.5743e+00,  2.2481e+01,  9.5220e+00, -1.7105e+01,
         -9.7326e+00, -1.1119e+01, -4.3147e+00,  1.0378e+01, -1.1291e+01],
        [-8.1786e-01, -5.0732e+00,  1.1131e+00,  1.5367e+00, -6.8010e+00,
         -1.6897e+00, -1.4885e+01,  1.4290e+01, -3.6512e+00,  3.5037e+00],
        [ 4.3767e+00, -1.3692e+01, -2.8827e+00, -2.1987e+00,  5.2604e+00,
         -4.4524e+00, -8.5432e+00,  7.8356e+00,  2.7013e+00,  1.1509e+01],
        [-4.4243e+00, -2.5095e+00,  2.4417e+00,  5.1099e+00,  2.3488e-01,
         -2.4453e+00, -8.1324e+00,  1.9674e+00,  9.8912e+00,  1.0405e+00],
        [-2.4942e+00, -5.1515e+00,  3.2324e+00,  1.7503e+01, -8.8999e+00,
          6.7007e+00, -1.5674e+01, -4.5069e+00,  4.8952e+00,  4.1086e+00],
        [-4.1155e+00, -9.5371e-01, -2.2361e+00,  1.6371e+00,  5.3208e+00,
         -3.8463e+00, -1.3077e+01,  3.8044e+00,  4.4508e+00,  1.0278e+01],
        [ 5.3836e-01, -7.6147e+00,  4.1683e+00,  9.0742e-01, -4.9478e+00,
          2.1632e-01, -3.8262e+00, -1.2726e-01,  8.9514e+00,  2.6435e+00],
        [ 1.8029e+01, -9.0732e-03,  7.6398e+00, -3.3392e+00, -5.4487e+00,
         -3.7254e+00,  9.9252e-01, -4.5629e+00, -5.6690e+00, -6.2320e+00],
        [-4.1986e+00, -1.8271e+00,  1.1728e+00,  1.6864e+01, -9.4361e+00,
          5.4890e+00, -1.0064e+01, -6.3521e+00,  4.3598e+00,  2.9531e+00],
        [-1.1661e+00, -5.9346e+00, -2.7398e+00, -8.9897e-01, -3.4615e+00,
          1.2762e+01,  5.1304e+00, -4.4104e+00,  5.7776e+00, -2.5341e-01],
        [-3.7052e+00, -1.2551e+00, -3.7971e+00, -3.7403e+00,  3.4972e+00,
          2.4683e-01, -9.5643e+00,  1.4226e+01, -1.4702e+00,  1.4871e+00],
        [ 3.5337e+00, -1.8027e+00, -7.3294e-01, -2.2463e+00, -1.8367e+00,
          2.7643e+00,  7.7153e+00, -3.7359e+00,  1.9144e+00, -3.2151e+00],
        [ 1.6859e+01, -8.4901e+00,  3.5055e-01, -1.0972e+01, -5.3222e+00,
         -6.3569e-01, -1.2760e+00,  1.1840e+00,  1.1671e+00,  4.0334e+00],
        [ 1.6218e+01, -3.9165e+00,  4.8932e+00, -6.6071e+00, -5.0144e+00,
         -4.0892e+00,  2.5246e+00,  7.6621e-02,  7.5244e-01, -5.1844e+00],
        [ 1.7087e+01, -8.3280e+00,  5.0402e+00, -3.7872e+00, -6.1715e+00,
         -1.0710e+00,  5.9537e-02, -1.4786e+00, -2.0892e+00, -1.4998e+00],
        [-1.7070e-01, -8.2267e-01, -3.5718e+00, -8.4674e+00,  1.7354e+01,
         -6.7771e+00,  2.5079e+00,  4.3964e+00,  6.9522e-02,  3.4801e+00],
        [-4.5785e+00,  7.4449e+00, -4.5273e-01,  1.6527e+00, -1.2585e+00,
         -2.0933e+00, -2.9657e+00,  9.6483e-01,  2.1849e+00, -1.6937e+00],
        [-7.5449e-01, -9.8284e+00, -4.0574e+00,  5.8278e+00,  3.1083e-01,
         -2.4886e+00, -1.3106e+01,  5.9464e+00,  1.0522e+00,  1.3026e+01],
        [-8.2718e+00, -4.7475e+00, -5.3733e+00,  4.2902e+00,  6.7510e+00,
          2.9172e+00, -1.5847e+01,  3.7327e+00,  6.2354e+00,  1.5046e+01],
        [-8.2544e+00,  9.1456e-01,  4.8561e+00,  2.1462e+01, -7.6738e+00,
         -3.4656e-01, -1.7607e+01, -1.1610e+00,  7.3160e+00,  2.4002e-02],
        [-5.2698e+00, -3.1882e+00,  2.3613e+00,  1.0723e+01, -2.7952e+00,
          9.9613e-01, -1.0023e+01,  1.9773e+00,  6.3883e+00,  1.1027e-01],
        [ 1.4605e-01,  5.3216e+00,  1.7021e+01,  3.2192e+00, -1.0712e+01,
         -8.2623e+00, -8.3164e+00, -2.5294e+00,  6.6627e+00, -5.7847e+00],
        [-4.8863e+00,  9.3220e+00, -2.3710e+00,  4.9483e-01, -1.5110e-01,
         -2.2597e+00, -2.9492e+00,  7.5625e-01,  2.9389e+00, -8.2468e-01],
        [-4.0061e+00, -8.4532e+00,  8.3371e+00,  3.5781e+00, -4.7813e+00,
         -2.9777e+00, -1.2871e+01,  4.5253e+00,  1.4371e+01,  2.9736e+00],
        [ 5.9474e-01, -3.3615e+00,  1.3987e+01,  5.2477e-01, -9.9553e+00,
         -6.1520e+00, -5.3818e+00,  5.7338e+00,  5.3644e+00, -7.3095e+00],
        [-4.3723e+00,  6.2039e+00, -1.2188e+00,  1.2263e+00,  3.7379e-01,
         -1.2315e+00, -2.2071e+00, -9.1887e-03,  1.0358e+00,  3.9357e-01],
        [-4.0810e+00,  3.0611e+00,  1.9250e+01,  7.1886e+00, -8.4233e+00,
         -5.5433e+00, -1.0845e+01, -2.5111e+00,  3.1536e+00, -5.6192e+00],
        [ 7.6877e-01,  1.5037e+00, -2.2954e+00, -1.2147e+00, -4.7480e-01,
          3.6270e+00,  1.1765e+01, -8.0027e+00,  3.8196e+00, -3.8871e+00],
        [-7.9454e+00,  3.8140e-01,  1.7573e+00,  9.3150e+00, -2.7677e+00,
          8.4209e-01, -1.0799e+01,  4.4895e+00,  2.7422e+00,  1.0227e+00],
        [-4.6408e+00, -4.7108e+00, -6.4358e+00,  3.9407e+00, -5.6671e+00,
          1.3467e+01, -2.4555e+00, -4.3068e-02,  2.3490e+00,  3.4176e+00],
        [-2.9136e+00,  3.0890e+00,  2.0559e+01,  6.0452e+00, -1.1518e+01,
         -9.4831e+00, -1.2910e+01,  1.4970e+00,  4.6435e+00, -6.7802e+00],
        [-1.9354e+00, -8.4041e+00, -9.3965e-02, -6.9148e-01,  5.2331e+00,
         -1.6379e+00, -3.8306e+00,  1.0853e+00,  1.5588e+00,  1.0850e+01],
        [-1.0620e+00,  2.6903e+00,  9.8037e+00,  4.4944e+00, -5.9174e+00,
         -1.5548e+00,  2.6822e+00, -1.0433e+01,  1.0641e+01, -4.5695e+00],
        [ 4.4587e-01, -2.5116e+00,  4.3537e+00,  3.3325e+00, -2.8542e+00,
         -4.7770e+00, -5.5153e+00, -1.4017e+00,  1.2280e+01,  6.2303e-01],
        [-4.0159e+00, -1.5814e+00,  2.1857e+00,  1.6229e+01, -4.9049e+00,
          4.5647e+00, -1.4763e+01, -3.0945e+00,  1.9740e+00,  3.1100e+00],
        [-2.0718e+00, -2.4445e+00, -3.3385e+00, -3.8961e+00,  1.7001e+01,
         -5.8615e+00, -4.2742e+00,  5.9109e+00,  3.8371e+00,  3.8939e+00],
        [-6.1109e+00,  1.9929e-03,  8.5358e+00,  1.1705e+01, -1.1507e+01,
         -4.8584e+00, -1.9585e+01,  1.0641e+01,  3.8145e+00, -1.7580e+00],
        [-1.0258e+01,  1.4564e+00, -3.1024e+00,  2.4257e+00,  9.7210e+00,
          2.0317e-01, -5.2403e+00,  2.6438e+00,  3.5774e+00,  4.8400e+00],
        [-8.1659e-01, -3.8095e+00,  1.0947e+01,  3.6587e+00, -7.8509e+00,
         -6.4447e+00, -9.4748e+00,  2.7998e+00,  8.3439e+00, -6.8371e-01],
        [-1.4709e+00, -7.5219e+00,  1.1796e+00,  3.3761e+00, -3.5446e+00,
          2.2485e+00, -3.6623e+00, -2.1193e+00,  1.2688e+01,  4.0085e+00],
        [ 9.9110e-01, -6.9509e+00, -2.5297e+00,  1.7999e+00, -5.3203e+00,
          1.2174e+01,  3.5452e+00, -5.3425e+00,  4.9313e+00,  1.2793e+00],
        [-1.7115e+00,  3.3311e+00,  3.5298e+00, -3.8093e+00,  1.5472e+01,
         -1.0909e+01, -3.6157e+00,  8.5901e+00, -8.0005e-01, -3.8194e+00]])
labels = torch.tensor([0, 6, 2, 5, 8, 7, 3, 1, 3, 8, 3, 4, 8, 7, 2, 9, 9, 8, 4, 8, 9, 1, 2, 7,
        9, 8, 3, 9, 8, 0, 3, 5, 7, 6, 0, 0, 0, 4, 1, 9, 9, 3, 3, 2, 1, 8, 2, 1,
        2, 6, 3, 5, 2, 9, 8, 8, 3, 4, 3, 4, 2, 8, 5, 4])
accuracy = (outputs.argmax(axis=1) == labels).sum()
print(outputs.argmax(axis=1))
print("Test accuracy:{0}".format(accuracy/len(labels)))
#准确率计算器

tensor([0, 6, 2, 5, 8, 7, 3, 1, 3, 8, 3, 4, 8, 7, 2, 9, 5, 8, 4, 8, 9, 1, 2, 7,
        9, 8, 3, 9, 8, 0, 3, 5, 7, 6, 0, 0, 0, 4, 1, 9, 9, 3, 3, 2, 1, 8, 2, 1,
        2, 6, 3, 5, 2, 9, 8, 8, 3, 4, 3, 4, 2, 8, 5, 4])
Test accuracy:0.984375
